### PR TITLE
BioData mining revisions

### PR DESCRIPTION
**Pull request by kathyxchen**
@dongbohu We are making revisions in response to a submission to BioData Mining. Will you be able to take a look at this PR sometime this week? Let me know if not and I can ask someone else to review! It should be pretty quick - mostly documentation additions and adding new Jupyter notebooks.

@cgreene I've added you as a reviewer so you can take a look at the k=24 Jupyter notebook. If you have a chance to read through that, let me know if I need to add anything. :) 

For the newly added Jupyter notebook, please review the notebook [here](https://github.com/kathyxchen/PathCORE-analysis/blob/biodata-mining-revisions/jupyter-notebooks/Supplemental3_TCGA_NMF_k%3D24.ipynb).
I've made small changes to the FastICA example (@dongbohu) [here](https://github.com/kathyxchen/PathCORE-analysis/blob/biodata-mining-revisions/jupyter-notebooks/Supplemental_PAO1_FastICA_example.ipynb) focused on making sure the text isn't weirdly formatted...

There's one more Jupyter notebook I need to create and push to this branch. I would like to have this done by EOD Tues.

### CODE REVIEW

**Comment by dongbohu** [comment]
@kathyxchen: Sure. I will take a look sometime this week.

**Review by dongbohu — APPROVED** [review]
The code looks reasonable. @cgreene, it will be great if you can also take a look at the two Jupyter notebook files. I don't really know what the expected results should look like.

**Review by cgreene — COMMENTED** [review]
I have reviewed the changes to the notebooks. I think we should do a test of overlap as well, but this is close! Probably one more commit to add that to the Summary notebook.

**Comment by kathyxchen** [comment]
Thanks @dongbohu and @cgreene!

I added the overlap-based networks to the notebook [here](https://github.com/kathyxchen/PathCORE-analysis/blob/1099c1c7191c996cf94b04886817fdb1dbca6d24/jupyter-notebooks/Summary_PAO1_and_TCGA_network_results.ipynb). Even after FDR correction there are a lot of edges in those networks since many of the pathways share genes. Let me know if this is what you meant?

**Comment by cgreene** [comment]
@kathyxchen : yea - that was what I meant. I expected it to be quite dense. I think you could write something like (for the Pseudomonas one):
"We compared the PathCORE-T network to a network constructed only from gene overlap (FDR corrected hypergeometric test < 0.05). The PathCORE-T network had 203 edges between 89 pathways. The overlap-based network had 406 edges between ?? pathways. However, the networks from PathCORE-T contained different edges: only 35 of the edges in the PathCORE-T networks were between pathways that shared genes and the average Jaccard Index was only 0.035."

You could write something similar, but with different numbers for TCGA. Perhaps this would help to address the reviewer concerns.

**Pull request merged**
